tasks:
- parallel:
  - upgrade-tasks
  - workload-tasks

upgrade-tasks:
  sequential:
  - cephadm.shell:
      env: [sha1]
      host.a:
        - ceph config set mon mon_warn_on_insecure_global_id_reclaim false --force
        - ceph config set mon mon_warn_on_insecure_global_id_reclaim_allowed false --force
        - ceph config set global log_to_journald false --force
        - ceph orch ps
        - ceph versions
        - ceph -s
        - ceph orch ls
        - ceph orch daemon redeploy "mgr.$(ceph mgr dump -f json | jq .standbys | jq .[] | jq -r .name)" --image quay.ceph.io/ceph-ci/ceph:$sha1
        - ceph orch ps --refresh
        - sleep 300
        - ceph orch ps
        - ceph versions
        - ceph -s
        - ceph versions | jq -e '.mgr | length == 2'
        - ceph mgr fail
        - sleep 180
        - ceph orch daemon redeploy "mgr.$(ceph mgr dump -f json | jq .standbys | jq .[] | jq -r .name)" --image quay.ceph.io/ceph-ci/ceph:$sha1
        - ceph orch ps --refresh
        - sleep 180
        - ceph orch ps
        - ceph versions
        - ceph -s
        - ceph mgr fail
        - sleep 300
        - ceph orch ps
        - ceph versions
        - ceph -s
        - ceph versions | jq -e '.mgr | length == 1'
        - ceph mgr fail
        - sleep 180
        - ceph orch ps
        - ceph versions
        - ceph orch upgrade start --image quay.ceph.io/ceph-ci/ceph:$sha1 --daemon-types mgr
        - while ceph orch upgrade status | jq '.in_progress' | grep true && ! ceph orch upgrade status | jq '.message' | grep Error ; do ceph orch ps ; ceph versions ; ceph orch upgrade status ; sleep 30 ; done
        - ceph versions | jq -e '.mgr | length == 1'
        - ceph versions | jq -e '.mgr | keys' | grep $sha1
        - ceph versions | jq -e '.overall | length == 2'
        - ceph orch upgrade check quay.ceph.io/ceph-ci/ceph:$sha1 | jq -e '.up_to_date | length == 2'
        - ceph orch ps --refresh
        - sleep 180
        - ceph config set mgr mgr/orchestrator/fail_fs true
        - ceph orch upgrade start --image quay.ceph.io/ceph-ci/ceph:$sha1
  - cephadm.shell:
      env: [sha1]
      host.a:
        - while ceph orch upgrade status | jq '.in_progress' | grep true && ! ceph orch upgrade status | jq '.message' | grep Error ; do ceph orch ps ; ceph versions ; ceph fs dump; ceph orch upgrade status ; sleep 30 ; done
        - ceph orch ps
        - ceph versions
        - echo "wait for servicemap items w/ changing names to refresh"
        - sleep 60
        - ceph orch ps
        - ceph health detail
        - ceph orch upgrade status
        - ceph versions
        - ceph versions | jq -e '.overall | length == 1'
        - ceph versions | jq -e '.overall | keys' | grep $sha1

workload-tasks:
  sequential:
  - workunit:
      clients:
        all:
          - suites/fsstress.sh
