---
version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: ceph:master   # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
  - base: nautilus
    upstream: ceph:nautilus # Required. Can be a branch in the same forked repo.
    assignees:              # Optional
      - "@rhcs/dashboard"
    reviewers:              # Optional
      - "@rhcs/dashboard"
label: ":arrow_heading_down: pull"  # Optional
