---
name: "Label doc/releases PRs so our backport GitHub Action picks them up"

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'doc/releases/**'

jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
      - name: Assign labels based on modified files
        uses: actions/labeler@9794b1493b6f1fa7b006c5f8635a19c76c98be95
        with:
          sync-labels: ''
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
